#!/bin/bash

HERE=`pwd`
DEPTH=../../../..

mv -v ${DEPTH}/initramfs/galaxytab/.git .

cd ${DEPTH}/kernel-tab
source env.sh
cd Kernel
MAKE_KERNEL
cd ${HERE}

mv -v .git ${DEPTH}/initramfs/galaxytab/
cp -v ${DEPTH}/kernel-tab/Kernel/arch/arm/boot/zImage .

